name: nlp_suite
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipywidgets
  - nltk
  
  - pip:
    - huggingface-hub
    - transformers
    - tokenizers
    - safetensors
    - gradio
    - hf-xet
    - groovy